title: Michelle C. Kelly
url: "http://michelleckelly.github.io"
baseurl: ""

markdown: kramdown
ins_logo: "https://github.com/michelleckelly.png"

tracking_id: UA-126125143-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Teaching"
   link: "/teaching/"
 - name: "Software"
   link: "/software/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
link: "contact"

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: michellekelly@ku.edu
  facebook:
  flickr:
  github: michelleckelly
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: michelleckelly2
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
googleplus: # anything in your profile username that comes after plus.google.com/
