title: Michelle C. Kelly
url: "http://michelleckelly.github.io"
baseurl: ""

markdown: kramdown
ins_logo: ""

tracking_id: UA-126125143-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Teaching"
   link: "/teaching/"
 - name: "Software"
   link: "/software/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
link: "contact"
