title: Michelle C. Kelly
url: "https://michelleckelly.github.io/"
baseurl: "https://michelleckelly.github.io/"

markdown: kramdown
ins_logo: ""

tracking_id: UA-126125143-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Teaching"
   link: "teaching"
 - name: "Research"
   link: "research"
 - name: "Software"
   link: "software"
 - name: "Contact"
   link: "contact"
